version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: tcs_app
    build:
      context: .
      dockerfile: Dockerfile
    command: make start
    ports:
      - "3000:8000"
    volumes:
      - ".:/app"
      - "/tmp:/tmp"

volumes:
  db:
    driver: local
